package com.poly.model;
// Generated Dec 2, 2019 1:22:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChiTietThu generated by hbm2java
 */
@Entity
@Table(name="ChiTietThu"
    ,schema="dbo"
    ,catalog="DuAn1"
)
public class ChiTietThu  implements java.io.Serializable {


     private ChiTietThuId id;
     private HoaDonThu hoaDonThu;
     private LoaiThu loaiThu;
     private int sotien;
     private Serializable mota;

    public ChiTietThu() {
    }

    public ChiTietThu(ChiTietThuId id, HoaDonThu hoaDonThu, LoaiThu loaiThu, int sotien, Serializable mota) {
       this.id = id;
       this.hoaDonThu = hoaDonThu;
       this.loaiThu = loaiThu;
       this.sotien = sotien;
       this.mota = mota;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="mahdthu", column=@Column(name="mahdthu", nullable=false) ), 
        @AttributeOverride(name="loaithu", column=@Column(name="loaithu", nullable=false) ) } )
    public ChiTietThuId getId() {
        return this.id;
    }
    
    public void setId(ChiTietThuId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mahdthu", nullable=false, insertable=false, updatable=false)
    public HoaDonThu getHoaDonThu() {
        return this.hoaDonThu;
    }
    
    public void setHoaDonThu(HoaDonThu hoaDonThu) {
        this.hoaDonThu = hoaDonThu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loaithu", nullable=false, insertable=false, updatable=false)
    public LoaiThu getLoaiThu() {
        return this.loaiThu;
    }
    
    public void setLoaiThu(LoaiThu loaiThu) {
        this.loaiThu = loaiThu;
    }

    
    @Column(name="sotien", nullable=false)
    public int getSotien() {
        return this.sotien;
    }
    
    public void setSotien(int sotien) {
        this.sotien = sotien;
    }

    
    @Column(name="mota", nullable=false)
    public Serializable getMota() {
        return this.mota;
    }
    
    public void setMota(Serializable mota) {
        this.mota = mota;
    }




}


