package com.poly.model;
// Generated Dec 2, 2019 1:22:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiThu generated by hbm2java
 */
@Entity
@Table(name="LoaiThu"
    ,schema="dbo"
    ,catalog="DuAn1"
)
public class LoaiThu  implements java.io.Serializable {


     private int maloaithu;
     private Serializable tenloaithu;
     private Serializable mota;
     private Set<ChiTietThu> chiTietThus = new HashSet<ChiTietThu>(0);

    public LoaiThu() {
    }

	
    public LoaiThu(int maloaithu) {
        this.maloaithu = maloaithu;
    }
    public LoaiThu(int maloaithu, Serializable tenloaithu, Serializable mota, Set<ChiTietThu> chiTietThus) {
       this.maloaithu = maloaithu;
       this.tenloaithu = tenloaithu;
       this.mota = mota;
       this.chiTietThus = chiTietThus;
    }
   
     @Id 

    
    @Column(name="maloaithu", unique=true, nullable=false)
    public int getMaloaithu() {
        return this.maloaithu;
    }
    
    public void setMaloaithu(int maloaithu) {
        this.maloaithu = maloaithu;
    }

    
    @Column(name="tenloaithu")
    public Serializable getTenloaithu() {
        return this.tenloaithu;
    }
    
    public void setTenloaithu(Serializable tenloaithu) {
        this.tenloaithu = tenloaithu;
    }

    
    @Column(name="mota")
    public Serializable getMota() {
        return this.mota;
    }
    
    public void setMota(Serializable mota) {
        this.mota = mota;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loaiThu")
    public Set<ChiTietThu> getChiTietThus() {
        return this.chiTietThus;
    }
    
    public void setChiTietThus(Set<ChiTietThu> chiTietThus) {
        this.chiTietThus = chiTietThus;
    }




}


