package com.poly.model;
// Generated Dec 2, 2019 1:22:06 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NguoiDung generated by hbm2java
 */
@Entity
@Table(name="NguoiDung"
    ,schema="dbo"
    ,catalog="DuAn1"
)
public class NguoiDung  implements java.io.Serializable {


     private String username;
     private String password;
     private String hoten;
     private boolean gioitinh;
     private Date ngaysinh;
     private String sodienthoai;
     private Boolean vaitro;
     private Set<HoaDonChi> hoaDonChis = new HashSet<HoaDonChi>(0);
     private Set<HoaDonThu> hoaDonThus = new HashSet<HoaDonThu>(0);

    public NguoiDung() {
    }

	
    public NguoiDung(String username, String hoten, boolean gioitinh) {
        this.username = username;
        this.hoten = hoten;
        this.gioitinh = gioitinh;
    }
    public NguoiDung(String username, String password, String hoten, boolean gioitinh, Date ngaysinh, String sodienthoai, Boolean vaitro, Set<HoaDonChi> hoaDonChis, Set<HoaDonThu> hoaDonThus) {
       this.username = username;
       this.password = password;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.ngaysinh = ngaysinh;
       this.sodienthoai = sodienthoai;
       this.vaitro = vaitro;
       this.hoaDonChis = hoaDonChis;
       this.hoaDonThus = hoaDonThus;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=10)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="hoten", nullable=false)
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    
    @Column(name="gioitinh", nullable=false)
    public boolean isGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(boolean gioitinh) {
        this.gioitinh = gioitinh;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaysinh", length=10)
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }

    
    @Column(name="sodienthoai", length=10)
    public String getSodienthoai() {
        return this.sodienthoai;
    }
    
    public void setSodienthoai(String sodienthoai) {
        this.sodienthoai = sodienthoai;
    }

    
    @Column(name="vaitro")
    public Boolean getVaitro() {
        return this.vaitro;
    }
    
    public void setVaitro(Boolean vaitro) {
        this.vaitro = vaitro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nguoiDung")
    public Set<HoaDonChi> getHoaDonChis() {
        return this.hoaDonChis;
    }
    
    public void setHoaDonChis(Set<HoaDonChi> hoaDonChis) {
        this.hoaDonChis = hoaDonChis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nguoiDung")
    public Set<HoaDonThu> getHoaDonThus() {
        return this.hoaDonThus;
    }
    
    public void setHoaDonThus(Set<HoaDonThu> hoaDonThus) {
        this.hoaDonThus = hoaDonThus;
    }




}


